// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet_core.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddressReq struct {
	Asset                string   `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressReq) Reset()         { *m = AddressReq{} }
func (m *AddressReq) String() string { return proto.CompactTextString(m) }
func (*AddressReq) ProtoMessage()    {}
func (*AddressReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e25c9835eecce9f, []int{0}
}

func (m *AddressReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressReq.Unmarshal(m, b)
}
func (m *AddressReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressReq.Marshal(b, m, deterministic)
}
func (m *AddressReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressReq.Merge(m, src)
}
func (m *AddressReq) XXX_Size() int {
	return xxx_messageInfo_AddressReq.Size(m)
}
func (m *AddressReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddressReq proto.InternalMessageInfo

func (m *AddressReq) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

type AddressResp struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressResp) Reset()         { *m = AddressResp{} }
func (m *AddressResp) String() string { return proto.CompactTextString(m) }
func (*AddressResp) ProtoMessage()    {}
func (*AddressResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e25c9835eecce9f, []int{1}
}

func (m *AddressResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressResp.Unmarshal(m, b)
}
func (m *AddressResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressResp.Marshal(b, m, deterministic)
}
func (m *AddressResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressResp.Merge(m, src)
}
func (m *AddressResp) XXX_Size() int {
	return xxx_messageInfo_AddressResp.Size(m)
}
func (m *AddressResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddressResp proto.InternalMessageInfo

func (m *AddressResp) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*AddressReq)(nil), "proto.addressReq")
	proto.RegisterType((*AddressResp)(nil), "proto.AddressResp")
}

func init() { proto.RegisterFile("wallet_core.proto", fileDescriptor_5e25c9835eecce9f) }

var fileDescriptor_5e25c9835eecce9f = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x4f, 0xcc, 0xc9,
	0x49, 0x2d, 0x89, 0x4f, 0xce, 0x2f, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05,
	0x53, 0x4a, 0x4a, 0x5c, 0x5c, 0x89, 0x29, 0x29, 0x45, 0xa9, 0xc5, 0xc5, 0x41, 0xa9, 0x85, 0x42,
	0x22, 0x5c, 0xac, 0x89, 0xc5, 0xc5, 0xa9, 0x25, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10,
	0x8e, 0x92, 0x3a, 0x17, 0xb7, 0x23, 0x4c, 0x4d, 0x71, 0x81, 0x90, 0x04, 0x17, 0x3b, 0x54, 0x0b,
	0x54, 0x19, 0x8c, 0x6b, 0x64, 0xc7, 0xc5, 0x15, 0x0e, 0xb6, 0xc8, 0x39, 0xbf, 0x28, 0x55, 0xc8,
	0x80, 0x8b, 0x1d, 0xaa, 0x4d, 0x48, 0x10, 0x62, 0xa9, 0x1e, 0xc2, 0x2a, 0x29, 0x21, 0xa8, 0x10,
	0x92, 0xc9, 0x49, 0x6c, 0x60, 0x21, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xee, 0x09, 0x91,
	0xc8, 0xaf, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WalletCoreClient is the client API for WalletCore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletCoreClient interface {
	Address(ctx context.Context, in *AddressReq, opts ...grpc.CallOption) (*AddressResp, error)
}

type walletCoreClient struct {
	cc *grpc.ClientConn
}

func NewWalletCoreClient(cc *grpc.ClientConn) WalletCoreClient {
	return &walletCoreClient{cc}
}

func (c *walletCoreClient) Address(ctx context.Context, in *AddressReq, opts ...grpc.CallOption) (*AddressResp, error) {
	out := new(AddressResp)
	err := c.cc.Invoke(ctx, "/proto.WalletCore/Address", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletCoreServer is the server API for WalletCore service.
type WalletCoreServer interface {
	Address(context.Context, *AddressReq) (*AddressResp, error)
}

func RegisterWalletCoreServer(s *grpc.Server, srv WalletCoreServer) {
	s.RegisterService(&_WalletCore_serviceDesc, srv)
}

func _WalletCore_Address_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletCoreServer).Address(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WalletCore/Address",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletCoreServer).Address(ctx, req.(*AddressReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _WalletCore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WalletCore",
	HandlerType: (*WalletCoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Address",
			Handler:    _WalletCore_Address_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet_core.proto",
}
