// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet_core.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddressReq struct {
	Asset                string   `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressReq) Reset()         { *m = AddressReq{} }
func (m *AddressReq) String() string { return proto.CompactTextString(m) }
func (*AddressReq) ProtoMessage()    {}
func (*AddressReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e25c9835eecce9f, []int{0}
}

func (m *AddressReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressReq.Unmarshal(m, b)
}
func (m *AddressReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressReq.Marshal(b, m, deterministic)
}
func (m *AddressReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressReq.Merge(m, src)
}
func (m *AddressReq) XXX_Size() int {
	return xxx_messageInfo_AddressReq.Size(m)
}
func (m *AddressReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddressReq proto.InternalMessageInfo

func (m *AddressReq) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

type AddressResp struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressResp) Reset()         { *m = AddressResp{} }
func (m *AddressResp) String() string { return proto.CompactTextString(m) }
func (*AddressResp) ProtoMessage()    {}
func (*AddressResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e25c9835eecce9f, []int{1}
}

func (m *AddressResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressResp.Unmarshal(m, b)
}
func (m *AddressResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressResp.Marshal(b, m, deterministic)
}
func (m *AddressResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressResp.Merge(m, src)
}
func (m *AddressResp) XXX_Size() int {
	return xxx_messageInfo_AddressResp.Size(m)
}
func (m *AddressResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddressResp proto.InternalMessageInfo

func (m *AddressResp) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type SignTxReq struct {
	Network              string   `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Asset                string   `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	From                 string   `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	VinAmount            int64    `protobuf:"varint,4,opt,name=vinAmount,proto3" json:"vinAmount,omitempty"`
	HexUnsignedTx        string   `protobuf:"bytes,5,opt,name=hexUnsignedTx,proto3" json:"hexUnsignedTx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignTxReq) Reset()         { *m = SignTxReq{} }
func (m *SignTxReq) String() string { return proto.CompactTextString(m) }
func (*SignTxReq) ProtoMessage()    {}
func (*SignTxReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e25c9835eecce9f, []int{2}
}

func (m *SignTxReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignTxReq.Unmarshal(m, b)
}
func (m *SignTxReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignTxReq.Marshal(b, m, deterministic)
}
func (m *SignTxReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignTxReq.Merge(m, src)
}
func (m *SignTxReq) XXX_Size() int {
	return xxx_messageInfo_SignTxReq.Size(m)
}
func (m *SignTxReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignTxReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignTxReq proto.InternalMessageInfo

func (m *SignTxReq) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *SignTxReq) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *SignTxReq) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SignTxReq) GetVinAmount() int64 {
	if m != nil {
		return m.VinAmount
	}
	return 0
}

func (m *SignTxReq) GetHexUnsignedTx() string {
	if m != nil {
		return m.HexUnsignedTx
	}
	return ""
}

type SignTxResp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	HexSignedTx          string   `protobuf:"bytes,2,opt,name=hexSignedTx,proto3" json:"hexSignedTx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignTxResp) Reset()         { *m = SignTxResp{} }
func (m *SignTxResp) String() string { return proto.CompactTextString(m) }
func (*SignTxResp) ProtoMessage()    {}
func (*SignTxResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e25c9835eecce9f, []int{3}
}

func (m *SignTxResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignTxResp.Unmarshal(m, b)
}
func (m *SignTxResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignTxResp.Marshal(b, m, deterministic)
}
func (m *SignTxResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignTxResp.Merge(m, src)
}
func (m *SignTxResp) XXX_Size() int {
	return xxx_messageInfo_SignTxResp.Size(m)
}
func (m *SignTxResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignTxResp.DiscardUnknown(m)
}

var xxx_messageInfo_SignTxResp proto.InternalMessageInfo

func (m *SignTxResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *SignTxResp) GetHexSignedTx() string {
	if m != nil {
		return m.HexSignedTx
	}
	return ""
}

type SendToAddressReq struct {
	Utxo                 []*SendToAddressReq_PreviousOutPoint `protobuf:"bytes,1,rep,name=utxo,proto3" json:"utxo,omitempty"`
	VinAmount            int64                                `protobuf:"varint,2,opt,name=vinAmount,proto3" json:"vinAmount,omitempty"`
	HexUnsignedTx        string                               `protobuf:"bytes,3,opt,name=hexUnsignedTx,proto3" json:"hexUnsignedTx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *SendToAddressReq) Reset()         { *m = SendToAddressReq{} }
func (m *SendToAddressReq) String() string { return proto.CompactTextString(m) }
func (*SendToAddressReq) ProtoMessage()    {}
func (*SendToAddressReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e25c9835eecce9f, []int{4}
}

func (m *SendToAddressReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendToAddressReq.Unmarshal(m, b)
}
func (m *SendToAddressReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendToAddressReq.Marshal(b, m, deterministic)
}
func (m *SendToAddressReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendToAddressReq.Merge(m, src)
}
func (m *SendToAddressReq) XXX_Size() int {
	return xxx_messageInfo_SendToAddressReq.Size(m)
}
func (m *SendToAddressReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendToAddressReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendToAddressReq proto.InternalMessageInfo

func (m *SendToAddressReq) GetUtxo() []*SendToAddressReq_PreviousOutPoint {
	if m != nil {
		return m.Utxo
	}
	return nil
}

func (m *SendToAddressReq) GetVinAmount() int64 {
	if m != nil {
		return m.VinAmount
	}
	return 0
}

func (m *SendToAddressReq) GetHexUnsignedTx() string {
	if m != nil {
		return m.HexUnsignedTx
	}
	return ""
}

type SendToAddressReq_PreviousOutPoint struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Txid                 string   `protobuf:"bytes,2,opt,name=txid,proto3" json:"txid,omitempty"`
	Index                uint32   `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendToAddressReq_PreviousOutPoint) Reset()         { *m = SendToAddressReq_PreviousOutPoint{} }
func (m *SendToAddressReq_PreviousOutPoint) String() string { return proto.CompactTextString(m) }
func (*SendToAddressReq_PreviousOutPoint) ProtoMessage()    {}
func (*SendToAddressReq_PreviousOutPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e25c9835eecce9f, []int{4, 0}
}

func (m *SendToAddressReq_PreviousOutPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendToAddressReq_PreviousOutPoint.Unmarshal(m, b)
}
func (m *SendToAddressReq_PreviousOutPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendToAddressReq_PreviousOutPoint.Marshal(b, m, deterministic)
}
func (m *SendToAddressReq_PreviousOutPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendToAddressReq_PreviousOutPoint.Merge(m, src)
}
func (m *SendToAddressReq_PreviousOutPoint) XXX_Size() int {
	return xxx_messageInfo_SendToAddressReq_PreviousOutPoint.Size(m)
}
func (m *SendToAddressReq_PreviousOutPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_SendToAddressReq_PreviousOutPoint.DiscardUnknown(m)
}

var xxx_messageInfo_SendToAddressReq_PreviousOutPoint proto.InternalMessageInfo

func (m *SendToAddressReq_PreviousOutPoint) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SendToAddressReq_PreviousOutPoint) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *SendToAddressReq_PreviousOutPoint) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func init() {
	proto.RegisterType((*AddressReq)(nil), "proto.addressReq")
	proto.RegisterType((*AddressResp)(nil), "proto.AddressResp")
	proto.RegisterType((*SignTxReq)(nil), "proto.SignTxReq")
	proto.RegisterType((*SignTxResp)(nil), "proto.SignTxResp")
	proto.RegisterType((*SendToAddressReq)(nil), "proto.SendToAddressReq")
	proto.RegisterType((*SendToAddressReq_PreviousOutPoint)(nil), "proto.SendToAddressReq.PreviousOutPoint")
}

func init() { proto.RegisterFile("wallet_core.proto", fileDescriptor_5e25c9835eecce9f) }

var fileDescriptor_5e25c9835eecce9f = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0x4d, 0x29, 0x1f, 0x32, 0x84, 0x04, 0x26, 0x44, 0x1b, 0xe2, 0xa1, 0x69, 0x4c, 0xec, 0x45,
	0x62, 0xf0, 0xea, 0x05, 0x48, 0xbc, 0x4a, 0x4a, 0xd5, 0xa3, 0x41, 0xbb, 0x42, 0x23, 0xec, 0xd6,
	0xdd, 0x2d, 0xf4, 0x7f, 0xf8, 0x4b, 0xfc, 0x5f, 0xfe, 0x08, 0xd3, 0xed, 0x6e, 0x0a, 0x04, 0xe2,
	0xa9, 0xfb, 0x5e, 0x67, 0xde, 0xee, 0x7b, 0x33, 0xd0, 0xdd, 0xce, 0x57, 0x2b, 0x22, 0x5f, 0xdf,
	0x19, 0x27, 0x83, 0x84, 0x33, 0xc9, 0xb0, 0xa6, 0x3e, 0x9e, 0x07, 0x30, 0x8f, 0x22, 0x4e, 0x84,
	0x08, 0xc8, 0x17, 0xf6, 0xa0, 0x36, 0x17, 0x82, 0x48, 0xc7, 0x72, 0x2d, 0xbf, 0x19, 0x14, 0xc0,
	0xbb, 0x86, 0xd6, 0xc8, 0xd4, 0x88, 0x04, 0x1d, 0x68, 0xe8, 0x16, 0x5d, 0x66, 0xa0, 0xf7, 0x6d,
	0x41, 0x73, 0x16, 0x2f, 0x68, 0x98, 0xe5, 0x62, 0x0e, 0x34, 0x28, 0x91, 0x5b, 0xc6, 0x3f, 0x4d,
	0x9d, 0x86, 0xe5, 0x35, 0x95, 0x9d, 0x6b, 0x10, 0xa1, 0xfa, 0xc1, 0xd9, 0xda, 0xb1, 0x15, 0xa9,
	0xce, 0x78, 0x09, 0xcd, 0x4d, 0x4c, 0x47, 0x6b, 0x96, 0x52, 0xe9, 0x54, 0x5d, 0xcb, 0xb7, 0x83,
	0x92, 0xc0, 0x2b, 0x68, 0x2f, 0x49, 0xf6, 0x44, 0x45, 0xbc, 0xa0, 0x24, 0x0a, 0x33, 0xa7, 0xa6,
	0x5a, 0xf7, 0x49, 0xef, 0x01, 0xc0, 0x3c, 0x4a, 0x24, 0x78, 0x0e, 0x75, 0x4e, 0x44, 0xba, 0x2a,
	0x3c, 0x9e, 0x05, 0x1a, 0xa1, 0x0b, 0xad, 0x25, 0xc9, 0x66, 0x46, 0xa9, 0x78, 0xd9, 0x2e, 0xe5,
	0xfd, 0x5a, 0xd0, 0x99, 0x11, 0x1a, 0x85, 0x6c, 0x54, 0x26, 0x76, 0x0f, 0xd5, 0x54, 0x66, 0xcc,
	0xb1, 0x5c, 0xdb, 0x6f, 0x0d, 0xfd, 0x22, 0xdc, 0xc1, 0x61, 0xd9, 0x60, 0xca, 0xc9, 0x26, 0x66,
	0xa9, 0x78, 0x4c, 0xe5, 0x94, 0xc5, 0x54, 0x06, 0xaa, 0x6b, 0xdf, 0x5e, 0xe5, 0x5f, 0x7b, 0xf6,
	0x11, 0x7b, 0xfd, 0x67, 0xe8, 0x1c, 0xaa, 0x9f, 0x1e, 0x51, 0x1e, 0xb2, 0xcc, 0xe2, 0x48, 0xfb,
	0x53, 0xe7, 0x7c, 0x1c, 0x31, 0x8d, 0x48, 0xa1, 0xdf, 0x0e, 0x0a, 0x30, 0xfc, 0xb1, 0x00, 0x5e,
	0xd4, 0xda, 0x4c, 0x18, 0x27, 0x78, 0x0b, 0x0d, 0xed, 0x07, 0xbb, 0xda, 0x65, 0xb9, 0x38, 0x7d,
	0xd4, 0xd4, 0xee, 0x9e, 0xdc, 0x40, 0xbd, 0xc8, 0x1d, 0x3b, 0x26, 0x16, 0xb3, 0x1b, 0xfd, 0xee,
	0x01, 0x23, 0x12, 0x1c, 0x43, 0x6f, 0x2f, 0xb6, 0xfc, 0xd7, 0x38, 0x9c, 0xe0, 0xc5, 0x89, 0x4c,
	0x8f, 0x68, 0xbc, 0xd5, 0x15, 0x73, 0xf7, 0x17, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x5f, 0xae, 0xf2,
	0xf0, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WalletCoreClient is the client API for WalletCore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletCoreClient interface {
	Address(ctx context.Context, in *AddressReq, opts ...grpc.CallOption) (*AddressResp, error)
	SignTx(ctx context.Context, in *SignTxReq, opts ...grpc.CallOption) (*SignTxResp, error)
	SendToAddressSignBTC(ctx context.Context, in *SendToAddressReq, opts ...grpc.CallOption) (*SignTxResp, error)
}

type walletCoreClient struct {
	cc *grpc.ClientConn
}

func NewWalletCoreClient(cc *grpc.ClientConn) WalletCoreClient {
	return &walletCoreClient{cc}
}

func (c *walletCoreClient) Address(ctx context.Context, in *AddressReq, opts ...grpc.CallOption) (*AddressResp, error) {
	out := new(AddressResp)
	err := c.cc.Invoke(ctx, "/proto.WalletCore/Address", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletCoreClient) SignTx(ctx context.Context, in *SignTxReq, opts ...grpc.CallOption) (*SignTxResp, error) {
	out := new(SignTxResp)
	err := c.cc.Invoke(ctx, "/proto.WalletCore/SignTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletCoreClient) SendToAddressSignBTC(ctx context.Context, in *SendToAddressReq, opts ...grpc.CallOption) (*SignTxResp, error) {
	out := new(SignTxResp)
	err := c.cc.Invoke(ctx, "/proto.WalletCore/SendToAddressSignBTC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletCoreServer is the server API for WalletCore service.
type WalletCoreServer interface {
	Address(context.Context, *AddressReq) (*AddressResp, error)
	SignTx(context.Context, *SignTxReq) (*SignTxResp, error)
	SendToAddressSignBTC(context.Context, *SendToAddressReq) (*SignTxResp, error)
}

func RegisterWalletCoreServer(s *grpc.Server, srv WalletCoreServer) {
	s.RegisterService(&_WalletCore_serviceDesc, srv)
}

func _WalletCore_Address_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletCoreServer).Address(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WalletCore/Address",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletCoreServer).Address(ctx, req.(*AddressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletCore_SignTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignTxReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletCoreServer).SignTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WalletCore/SignTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletCoreServer).SignTx(ctx, req.(*SignTxReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletCore_SendToAddressSignBTC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToAddressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletCoreServer).SendToAddressSignBTC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WalletCore/SendToAddressSignBTC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletCoreServer).SendToAddressSignBTC(ctx, req.(*SendToAddressReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _WalletCore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WalletCore",
	HandlerType: (*WalletCoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Address",
			Handler:    _WalletCore_Address_Handler,
		},
		{
			MethodName: "SignTx",
			Handler:    _WalletCore_SignTx_Handler,
		},
		{
			MethodName: "SendToAddressSignBTC",
			Handler:    _WalletCore_SendToAddressSignBTC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet_core.proto",
}
